{% set name = "tox-poetry-installer" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 83d6b4cdd61db2354d5f9dfecefb79bf160ac5f8c745967d9ebda968ce4f5777

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - poetry-core >=1.1.0
    - pip
  run:
    - python >=3.7
    - poetry-core >=1.1.0
    - tox >=3.8.0,<4.0.0
  run_constrained:
    - cleo >=1.0.0
    - poetry >=1.2.0
test:
  imports:
    - tox_poetry_installer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/enpaul/tox-poetry-installer/
  summary: A plugin for Tox that lets you install test environment dependencies from the Poetry lockfile
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
